---
title: "DEG0126BubblePlot"
output: html_document
date: "2024-01-26"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r}
V1 <- read.csv("combined_df_V1.csv", row.names = 1)
colnames(V1)[2] <- "expressed_cells_pct"
V2 <- read.csv("combined_df_V2.csv", row.names = 1)
colnames(V2)[2] <- "expressed_cells_pct"
```

```{r}
meanExp1 <- data.frame(mean_exp = V1$mean.expression, area = V1$area, gene = rownames(V1))
meanExp2 <- data.frame(mean_exp = V2$mean.expression, area = V2$area, gene = rownames(V2))

exp_cell1 <- data.frame(exp_cell = V1$expressed_cells_pct, area = V1$area, gene = rownames(V1))
exp_cell2 <- data.frame(exp_cell = V2$expressed_cells_pct, area = V2$area, gene = rownames(V2))
```

```{r}
combined_meanExp <- rbind(meanExp1, meanExp2)
combined_exp_cell <- rbind(exp_cell1, exp_cell2)
```

```{r}
# Combine the reshaped data frames by gene and cluster
df_combined <- full_join(combined_meanExp, combined_exp_cell, by = c('gene', 'area'))
df_combined$gene <- factor(df_combined$gene, levels = rev(df_combined$gene[1:40])) # 20/40
```

```{r}
# Create the bubble plot
ggplot(df_combined, aes(x = gene, y = area, size = exp_cell, color = mean_exp)) +
  geom_point() +
  scale_size_continuous(range = c(1, 10)) + # Adjust according to your data
  scale_color_gradient(low = "yellow", high = "blue") + # Adjust color gradient
  theme_bw() +  # White background theme
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    axis.text.y = element_text(hjust = 1),
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    legend.position = "right"
  ) +
  labs(
    x = 'Gene', 
    y = 'Cluster', 
    size = 'Proportion Expressed (%)', 
    color = 'Mean Expression'
  ) +
  guides(
    color = guide_colorbar(title = 'Mean expression', title.position = 'top', title.hjust = 0.5),
    size = guide_legend(title = 'Percentage of expressed cells (%)', title.position = 'top', title.hjust = 0.5)
  ) +
  coord_flip()  # Flip the axes
ggsave("Top20EN_Mig_Expbubbleplot.pdf", width = 5, height = 14) # 8/14
```

